export interface QuizQuestion {
  question: string;
  options: string[];
  answer: number;
}

export interface QuizSubject {
  id: string;
  name: string;
  emoji: string;
  questions: QuizQuestion[];
}

export const quizSubjects: QuizSubject[] = [
  {
    id: "math",
    name: "Math",
    emoji: "🔢",
    questions: [
      { question: "What is 1108 × 2019?", options: ["2237052", "2235072", "2247052", "2238052"], answer: 0 },
      { question: "What is 11¹¹ mod 100?", options: ["11", "71", "31", "51"], answer: 1 },
      { question: "Find x: 3x² − 12x + 9 = 0", options: ["x = 1 or 3", "x = 2 or 4", "x = 3 or 5", "x = 0 or 6"], answer: 0 },
      { question: "What is the derivative of x³ + 2x² − 5x?", options: ["3x² + 4x − 5", "3x² + 2x − 5", "x² + 4x − 5", "3x + 4x² − 5"], answer: 0 },
      { question: "What is ∫(2x + 3)dx?", options: ["x² + 3x + C", "2x² + 3x + C", "x² + 3 + C", "2x + 3x + C"], answer: 0 },
      { question: "If log₂(x) = 10, what is x?", options: ["512", "1024", "2048", "100"], answer: 1 },
      { question: "What is the sum of the first 100 natural numbers?", options: ["5000", "5050", "5100", "4950"], answer: 1 },
      { question: "What is 17! / 15!?", options: ["272", "256", "240", "289"], answer: 0 },
      { question: "In triangle ABC, if a=5, b=12, c=13, what type is it?", options: ["Right", "Acute", "Obtuse", "Equilateral"], answer: 0 },
      { question: "What is the determinant of [[3,1],[5,2]]?", options: ["1", "−1", "11", "6"], answer: 0 },
      { question: "Solve: |2x − 7| = 11", options: ["x = 9 or −2", "x = 9 or 2", "x = −9 or 2", "x = 3 or −3"], answer: 0 },
      { question: "What is the 20th term of AP: 3, 7, 11, …?", options: ["79", "83", "75", "81"], answer: 0 },
      { question: "What is sin(π/6) + cos(π/3)?", options: ["1", "0.5", "1.5", "0"], answer: 0 },
      { question: "How many diagonals does a 12-sided polygon have?", options: ["54", "48", "60", "66"], answer: 0 },
      { question: "What is the GCD of 462 and 1071?", options: ["21", "3", "7", "42"], answer: 0 },
      { question: "If f(x) = e^(2x), what is f'(x)?", options: ["2e^(2x)", "e^(2x)", "2xe^(2x)", "e^(x)"], answer: 0 },
      { question: "What is the value of C(10,4)?", options: ["210", "120", "252", "200"], answer: 0 },
      { question: "What is √(2025)?", options: ["45", "44", "46", "43"], answer: 0 },
      { question: "Solve: x³ − 6x² + 11x − 6 = 0", options: ["1, 2, 3", "2, 3, 4", "1, 3, 5", "0, 2, 3"], answer: 0 },
      { question: "What is the area of a circle with radius 7 (use π=22/7)?", options: ["154", "144", "148", "156"], answer: 0 },
    ],
  },
  {
    id: "english",
    name: "English",
    emoji: "📖",
    questions: [
      { question: "What figure of speech: 'The world is a stage'?", options: ["Metaphor", "Simile", "Hyperbole", "Irony"], answer: 0 },
      { question: "Identify the subjunctive: 'If I ___ rich, I'd travel.'", options: ["were", "was", "am", "be"], answer: 0 },
      { question: "What is a 'soliloquy'?", options: ["Speech to oneself on stage", "A group conversation", "A rhyme scheme", "A type of poem"], answer: 0 },
      { question: "'Ephemeral' means:", options: ["Short-lived", "Eternal", "Beautiful", "Dangerous"], answer: 0 },
      { question: "Which is an oxymoron?", options: ["Deafening silence", "Bright sun", "Cold ice", "Dark night"], answer: 0 },
      { question: "'She sells seashells' is an example of:", options: ["Alliteration", "Assonance", "Onomatopoeia", "Metaphor"], answer: 0 },
      { question: "What is the passive voice of 'She wrote the letter'?", options: ["The letter was written by her", "The letter is written by her", "The letter wrote her", "She was written the letter"], answer: 0 },
      { question: "What type of clause: 'Although it rained, we went out'?", options: ["Concessive", "Causal", "Temporal", "Conditional"], answer: 0 },
      { question: "'Ubiquitous' means:", options: ["Present everywhere", "Very rare", "Unique", "Underground"], answer: 0 },
      { question: "What is synecdoche?", options: ["Part represents the whole", "Exaggeration", "Contradiction", "Comparison using like"], answer: 0 },
      { question: "The word 'pneumonia' has a:", options: ["Silent 'p'", "Silent 'n'", "Silent 'e'", "Silent 'a'"], answer: 0 },
      { question: "'To kill two birds with one stone' is:", options: ["An idiom", "A proverb", "A simile", "Alliteration"], answer: 0 },
      { question: "What tense: 'She will have been working for 5 hours'?", options: ["Future perfect continuous", "Future continuous", "Past perfect", "Present perfect"], answer: 0 },
      { question: "A 'bildungsroman' is:", options: ["A coming-of-age novel", "A mystery genre", "A type of sonnet", "A Greek tragedy"], answer: 0 },
      { question: "'Sanguine' means:", options: ["Optimistic", "Angry", "Sad", "Fearful"], answer: 0 },
      { question: "What is an 'unreliable narrator'?", options: ["A narrator whose credibility is compromised", "An omniscient narrator", "A third-person narrator", "The author"], answer: 0 },
      { question: "Which is correct?", options: ["Whom did you call?", "Who did you call?", "Whose did you call?", "Which did you call?"], answer: 0 },
      { question: "'Cacophony' means:", options: ["Harsh, discordant sounds", "Beautiful music", "Silence", "Rhythm"], answer: 0 },
      { question: "What is an 'anaphora'?", options: ["Repetition at the start of clauses", "Repetition at the end", "A type of rhyme", "An exclamation"], answer: 0 },
      { question: "What literary device: 'The thunder roared angrily'?", options: ["Personification", "Simile", "Alliteration", "Irony"], answer: 0 },
    ],
  },
  {
    id: "hindi",
    name: "Hindi",
    emoji: "🇮🇳",
    questions: [
      { question: "'श्लेष अलंकार' का उदाहरण कौन-सा है?", options: ["रहिमन पानी राखिये", "चरण-कमल", "काली घटा", "तेरे नैन"], answer: 0 },
      { question: "'सर्वनाम' के कितने भेद हैं?", options: ["6", "5", "4", "8"], answer: 0 },
      { question: "'उत्प्रेक्षा अलंकार' में कौन-सा शब्द प्रयुक्त होता है?", options: ["मानो/जानो", "जैसे", "सा/सी", "और"], answer: 0 },
      { question: "'कर्मधारय समास' का उदाहरण क्या है?", options: ["नीलकमल", "राजपुत्र", "दशानन", "चौराहा"], answer: 0 },
      { question: "'वीर रस' का स्थायी भाव क्या है?", options: ["उत्साह", "क्रोध", "भय", "शोक"], answer: 0 },
      { question: "'अव्ययीभाव समास' का उदाहरण है:", options: ["यथाशक्ति", "पंचवटी", "नीलकमल", "राजपुत्र"], answer: 0 },
      { question: "'द्विगु समास' में क्या होता है?", options: ["पहला पद संख्यावाची", "दूसरा पद संख्यावाची", "दोनों संज्ञा", "कोई क्रिया"], answer: 0 },
      { question: "'रस' के कितने अंग होते हैं?", options: ["4", "3", "5", "6"], answer: 0 },
      { question: "संधि के कितने भेद हैं?", options: ["3", "4", "5", "2"], answer: 0 },
      { question: "'विद्यालय' में कौन-सी संधि है?", options: ["दीर्घ संधि", "गुण संधि", "वृद्धि संधि", "यण संधि"], answer: 0 },
      { question: "'महाकाव्य' और 'खंडकाव्य' में क्या अंतर है?", options: ["सर्गों की संख्या", "भाषा", "रस", "छंद"], answer: 0 },
      { question: "'कबीर' किस काल के कवि हैं?", options: ["भक्तिकाल", "रीतिकाल", "आदिकाल", "आधुनिक काल"], answer: 0 },
      { question: "'छंद' के कितने प्रकार हैं?", options: ["2 (मात्रिक और वर्णिक)", "3", "4", "5"], answer: 0 },
      { question: "'तत्सम' शब्द का उदाहरण:", options: ["कार्य", "काम", "घर", "पानी"], answer: 0 },
      { question: "'उपसर्ग' क्या करता है?", options: ["शब्द के आरंभ में जुड़कर अर्थ बदलता है", "अंत में जुड़ता है", "बीच में जुड़ता है", "कुछ नहीं करता"], answer: 0 },
      { question: "'प्रत्यय' कहाँ जोड़ा जाता है?", options: ["शब्द के अंत में", "शब्द के आरंभ में", "बीच में", "कहीं भी"], answer: 0 },
      { question: "'अनुस्वार' का चिह्न क्या है?", options: ["ं", "ँ", "ः", "्"], answer: 0 },
      { question: "'विलोम' शब्द - 'आदि' का विलोम:", options: ["अंत", "मध्य", "प्रारंभ", "शुरू"], answer: 0 },
      { question: "'मुहावरा' - 'आँखों का तारा' का अर्थ:", options: ["बहुत प्रिय", "आँख में दर्द", "तारा देखना", "रात होना"], answer: 0 },
      { question: "'रामचरितमानस' के रचयिता कौन हैं?", options: ["तुलसीदास", "सूरदास", "कबीर", "रहीम"], answer: 0 },
    ],
  },
  {
    id: "evs",
    name: "EVS",
    emoji: "🌍",
    questions: [
      { question: "What is the pH of pure water at 25°C?", options: ["7", "6", "8", "5"], answer: 0 },
      { question: "Which layer of the atmosphere contains the ozone layer?", options: ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"], answer: 0 },
      { question: "What is the process by which rocks are broken down by weather?", options: ["Weathering", "Erosion", "Deposition", "Sedimentation"], answer: 0 },
      { question: "Which greenhouse gas has the highest global warming potential per molecule?", options: ["SF₆", "CO₂", "CH₄", "N₂O"], answer: 0 },
      { question: "What is biomagnification?", options: ["Increase of toxin concentration up food chain", "Growth of organisms", "Photosynthesis rate", "Water purification"], answer: 0 },
      { question: "The Kyoto Protocol deals with:", options: ["Climate change mitigation", "Biodiversity", "Ozone depletion", "Desertification"], answer: 0 },
      { question: "What is the most abundant gas in Earth's atmosphere?", options: ["Nitrogen", "Oxygen", "Argon", "CO₂"], answer: 0 },
      { question: "Which biome has the highest biodiversity?", options: ["Tropical rainforest", "Desert", "Tundra", "Taiga"], answer: 0 },
      { question: "What causes acid rain?", options: ["SO₂ and NOₓ emissions", "CO₂ only", "Methane", "Water vapor"], answer: 0 },
      { question: "What is the Coriolis effect?", options: ["Deflection of moving objects due to Earth's rotation", "Gravitational pull", "Magnetic field effect", "Tidal force"], answer: 0 },
      { question: "What is eutrophication?", options: ["Excess nutrients causing algal bloom", "Soil erosion", "Air pollution", "Deforestation"], answer: 0 },
      { question: "Which is a renewable energy source?", options: ["Geothermal", "Coal", "Natural gas", "Petroleum"], answer: 0 },
      { question: "What is the primary cause of coral bleaching?", options: ["Rising ocean temperatures", "Overfishing", "Plastic pollution", "Oil spills"], answer: 0 },
      { question: "What does BOD measure in water?", options: ["Biological oxygen demand", "Bacterial count", "pH level", "Temperature"], answer: 0 },
      { question: "Which soil type has the smallest particle size?", options: ["Clay", "Sand", "Silt", "Gravel"], answer: 0 },
      { question: "What is the water cycle process where water becomes vapor?", options: ["Evaporation", "Condensation", "Precipitation", "Infiltration"], answer: 0 },
      { question: "What is an ecological niche?", options: ["An organism's role in its ecosystem", "A type of habitat", "A food chain", "A biome"], answer: 0 },
      { question: "Which convention protects wetlands?", options: ["Ramsar Convention", "CITES", "Basel Convention", "Montreal Protocol"], answer: 0 },
      { question: "What is the main cause of desertification?", options: ["Overgrazing and deforestation", "Volcanic activity", "Earthquakes", "Floods"], answer: 0 },
      { question: "What percentage of Earth's water is freshwater?", options: ["~2.5%", "~10%", "~25%", "~50%"], answer: 0 },
    ],
  },
  {
    id: "cs",
    name: "Computer Science",
    emoji: "💻",
    questions: [
      { question: "What is the time complexity of binary search?", options: ["O(log n)", "O(n)", "O(n²)", "O(1)"], answer: 0 },
      { question: "What data structure uses LIFO?", options: ["Stack", "Queue", "Array", "Tree"], answer: 0 },
      { question: "What is a deadlock in OS?", options: ["Processes waiting for each other indefinitely", "A crashed program", "Memory overflow", "CPU overheating"], answer: 0 },
      { question: "What does DNS stand for?", options: ["Domain Name System", "Data Network Service", "Digital Name Server", "Domain Network System"], answer: 0 },
      { question: "Which sorting algorithm has worst-case O(n log n)?", options: ["Merge Sort", "Quick Sort", "Bubble Sort", "Selection Sort"], answer: 0 },
      { question: "What is polymorphism in OOP?", options: ["Same interface, different implementations", "Data hiding", "Inheritance only", "Creating objects"], answer: 0 },
      { question: "What is the purpose of an index in a database?", options: ["Speed up data retrieval", "Store data", "Delete records", "Create tables"], answer: 0 },
      { question: "What is a race condition?", options: ["Output depends on timing of uncontrolled events", "A fast algorithm", "Network latency", "Memory leak"], answer: 0 },
      { question: "What does TCP guarantee that UDP does not?", options: ["Reliable, ordered delivery", "Speed", "Broadcasting", "Encryption"], answer: 0 },
      { question: "What is the halting problem?", options: ["Whether a program will finish or run forever — undecidable", "A sorting problem", "A graph problem", "Memory allocation"], answer: 0 },
      { question: "What is Big-O of accessing an element in a hash table (avg)?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], answer: 0 },
      { question: "What is normalization in databases?", options: ["Reducing data redundancy", "Adding more tables", "Deleting data", "Encrypting data"], answer: 0 },
      { question: "What is a semaphore used for?", options: ["Process synchronization", "Memory allocation", "File compression", "Network routing"], answer: 0 },
      { question: "What is the difference between process and thread?", options: ["Thread shares memory within a process", "They are the same", "Process is faster", "Thread has its own memory"], answer: 0 },
      { question: "What is dynamic programming?", options: ["Solving problems by breaking into overlapping subproblems", "Real-time programming", "Object-oriented design", "Functional programming"], answer: 0 },
      { question: "What is a B-tree used for?", options: ["Database indexing", "Sorting arrays", "Graph traversal", "Hashing"], answer: 0 },
      { question: "What is the CAP theorem?", options: ["Consistency, Availability, Partition tolerance — pick 2", "A sorting theorem", "A graph theory rule", "An encryption standard"], answer: 0 },
      { question: "What is a virtual memory?", options: ["Using disk as extended RAM", "Cloud storage", "Cache memory", "ROM"], answer: 0 },
      { question: "What is Dijkstra's algorithm used for?", options: ["Shortest path in a graph", "Sorting", "Searching", "Hashing"], answer: 0 },
      { question: "What is the OSI model's Layer 4?", options: ["Transport", "Network", "Session", "Data Link"], answer: 0 },
    ],
  },
  {
    id: "ai",
    name: "AI",
    emoji: "🤖",
    questions: [
      { question: "What is the vanishing gradient problem?", options: ["Gradients become too small during backpropagation", "Network runs too fast", "Data is lost", "Overfitting"], answer: 0 },
      { question: "What activation function solves vanishing gradients?", options: ["ReLU", "Sigmoid", "Tanh", "Softmax"], answer: 0 },
      { question: "What is a GAN?", options: ["Generative Adversarial Network", "General AI Network", "Gradient Analysis Node", "Graph Attention Network"], answer: 0 },
      { question: "What does 'overfitting' mean?", options: ["Model memorizes training data, poor generalization", "Model is too simple", "Training is too fast", "Data is too clean"], answer: 0 },
      { question: "What is the purpose of dropout in neural networks?", options: ["Regularization to prevent overfitting", "Speed up training", "Increase accuracy", "Reduce data size"], answer: 0 },
      { question: "What is transfer learning?", options: ["Using a pre-trained model for a new task", "Moving data between servers", "Translating languages", "Copying code"], answer: 0 },
      { question: "What is the 'attention mechanism' in transformers?", options: ["Weighing importance of different input parts", "Focus on one layer", "Skip connections", "Batch normalization"], answer: 0 },
      { question: "What is reinforcement learning?", options: ["Agent learns by reward/punishment from environment", "Supervised classification", "Unsupervised clustering", "Data preprocessing"], answer: 0 },
      { question: "What is a confusion matrix used for?", options: ["Evaluating classification model performance", "Matrix multiplication", "Data storage", "Feature extraction"], answer: 0 },
      { question: "What does BERT stand for?", options: ["Bidirectional Encoder Representations from Transformers", "Binary Encoded Recursive Transformer", "Basic Entity Recognition Tool", "Batch Encoded Representation"], answer: 0 },
      { question: "What is the curse of dimensionality?", options: ["Performance degrades with too many features", "Too few data points", "Slow hardware", "Network latency"], answer: 0 },
      { question: "What is an epoch in training?", options: ["One complete pass through the training data", "A single batch", "One gradient update", "A time period"], answer: 0 },
      { question: "What is the difference between precision and recall?", options: ["Precision: correct positive predictions; Recall: actual positives found", "They are the same", "Precision is always higher", "Recall measures speed"], answer: 0 },
      { question: "What is a convolutional neural network best for?", options: ["Image recognition", "Text generation", "Audio only", "Database queries"], answer: 0 },
      { question: "What is backpropagation?", options: ["Computing gradients to update weights", "Forward pass only", "Data augmentation", "Feature scaling"], answer: 0 },
      { question: "What is the Turing Test?", options: ["Test if a machine can exhibit human-like intelligence", "A sorting algorithm", "A hardware benchmark", "A programming language"], answer: 0 },
      { question: "What is few-shot learning?", options: ["Learning from very few examples", "Training with large datasets", "Unsupervised learning", "Reinforcement learning"], answer: 0 },
      { question: "What is the purpose of batch normalization?", options: ["Stabilize and speed up training", "Reduce model size", "Increase data", "Remove layers"], answer: 0 },
      { question: "What is an autoencoder?", options: ["Neural network that learns compressed representations", "A code generator", "A search engine", "A database"], answer: 0 },
      { question: "What is the F1 score?", options: ["Harmonic mean of precision and recall", "Accuracy squared", "Loss function", "Learning rate"], answer: 0 },
    ],
  },
];
